// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
import type { NextApiRequest, NextApiResponse } from "next";

interface Product {}

const products: Product[] = [
  {
    id: "1",
    name: "Camiseta Mescla",
    price: 28.8,
    parcelamento: [3, 9.33],
    color: "Cinza",
    image: "/img/img_2.png",
    size: "M",
    date: "1995-12-17",
  },
  {
    id: "2",
    name: "Saia em couro",
    price: 398.0,
    parcelamento: [5, 30],
    color: "Preto",
    image: "/img/img_3.png",
    size: "G",
    date: "1996-12-17",
  },
  {
    id: "3",
    name: "Cardigan Tigre",
    price: 398.8,
    parcelamento: [5, 30],
    color: "Laranja",
    image: "/img/img_4.png",
    size: "GG",
    date: "1997-12-17",
  },
  {
    id: "4",
    name: "Cardigan off white",
    price: 99.9,
    parcelamento: [3, 33.3],
    color: "Branco",
    image: "/img/img_5.png",
    size: "U",
    date: "1998-12-17",
  },
  {
    id: "5",
    name: "Body Leopardo",
    price: 129.9,
    parcelamento: [3, 43.43],
    color: "Amarelo",
    image: "/img/img_6.png",
    size: "M",
    date: "1999-12-17",
  },
  {
    id: "6",
    name: "Casaco Pelos",
    price: 398.0,
    parcelamento: [5, 30],
    color: "Rosa",
    image: "/img/img_7.png",
    size: "GG",
    date: "1999-12-16",
  },
  {
    id: "7",
    name: "Cropped Stripes",
    price: 120.0,
    parcelamento: [3, 40],
    color: "Amarelo",
    image: "/img/img_8.png",
    size: "U",
    date: "2000-12-17",
  },
  {
    id: "8",
    name: "Camisa Transparente",
    price: 398.0,
    parcelamento: [5, 30],
    color: "Preto",
    image: "/img/img_9.png",
    size: "P",
    date: "2000-11-17",
  },
  {
    id: "9",
    name: "Pochete Clutch",
    price: 99.0,
    parcelamento: [3, 33],
    color: "Preto",
    image: "/img/img_10.png",
    size: "M",
    date: "2003-12-17",
  },
  {
    id: "9",
    name: "Pochete Clutch",
    price: 99.0,
    parcelamento: [3, 33],
    color: "Preto",
    image: "/img/img_10.png",
    size: "M",
    date: "2003-12-17",
  },
  {
    id: "9",
    name: "Pochete Clutch",
    price: 99.0,
    parcelamento: [3, 33],
    color: "Preto",
    image: "/img/img_10.png",
    size: "M",
    date: "2003-12-17",
  },
  {
    id: "9",
    name: "Pochete Clutch",
    price: 99.0,
    parcelamento: [3, 33],
    color: "Preto",
    image: "/img/img_10.png",
    size: "M",
    date: "2003-12-17",
  },
  {
    id: "9",
    name: "Pochete Clutch",
    price: 99.0,
    parcelamento: [3, 33],
    color: "Preto",
    image: "/img/img_10.png",
    size: "M",
    date: "2003-12-17",
  },
  {
    id: "9",
    name: "Pochete Clutch",
    price: 99.0,
    parcelamento: [3, 33],
    color: "Preto",
    image: "/img/img_10.png",
    size: "M",
    date: "2003-12-17",
  },
];

export default function handler(
  req: NextApiRequest,
  res: NextApiResponse<{ products: Product[] }>
) {
  res.status(200).json({ products });
}
